# build environment
FROM node:9.6.1 as builder
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
RUN npm install --silent
RUN npm install react-scripts@1.1.1 -g --silent
COPY . /usr/src/app
RUN npm run build

# production environment
FROM nginx:1.15.8
COPY --from=builder /usr/src/app/build /usr/share/nginx/html
# assumps user  nginx
RUN touch /var/run/nginx.pid && \
  chown -R 1001:0 /var/run/nginx.pid && \
  chown -R 1001:0 /var/cache/nginx
RUN chmod -R 777 /var/cache/nginx

#USER nginx

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
