// // Län och kommuner 2018
// // Counties and municipalities 2018

export const countiesAndMunicipalities = [
  { key: 'everywhere', text: 'Hela Sverige', value: 'Hela Sverige' },

  { key: 'stockholms_lan', text: 'Stockholms län', value: '01' },
  { key: 'upplands_vasby', text: 'Upplands Väsby', value: '0114' },
  { key: 'vallentuna', text: 'Vallentuna', value: '0115' },
  { key: 'osteraker', text: 'Österåker', value: '0117' },
  { key: 'varmdo', text: 'Värmdö', value: '0120' },
  { key: 'jarfalla', text: 'Järfälla', value: '0123' },
  { key: 'ekero', text: 'Ekerö', value: '0125' },
  { key: 'huddinge', text: 'Huddinge', value: '0126' },
  { key: 'botkyrka', text: 'Botkyrka', value: '0127' },
  { key: 'salem', text: 'Salem', value: '0128' },
  { key: 'haninge', text: 'Haninge', value: '0136' },
  { key: 'tyreso', text: 'Tyresö', value: '0138' },
  { key: 'upplands-bro', text: 'Upplands-Bro', value: '0139' },
  { key: 'nykvarn', text: 'Nykvarn', value: '0140' },
  { key: 'taby', text: 'Täby', value: '0160' },
  { key: 'danderyd', text: 'Danderyd', value: '0162' },
  { key: 'sollentuna', text: 'Sollentuna', value: '0163' },
  { key: 'stockholm', text: 'Stockholm', value: '0180' },
  { key: 'sodertalje', text: 'Södertälje', value: '0181' },
  { key: 'nacka', text: 'Nacka', value: '0182' },
  { key: 'sundbyberg', text: 'Sundbyberg', value: '0183' },
  { key: 'solna', text: 'Solna', value: '0184' },
  { key: 'lidingo', text: 'Lidingö', value: '0186' },
  { key: 'vaxholm', text: 'Vaxholm', value: '0187' },
  { key: 'norrtalje', text: 'Norrtälje', value: '0188' },
  { key: 'sigtuna', text: 'Sigtuna', value: '0191' },
  { key: 'nynashamn', text: 'Nynäshamn', value: '0192' },

  { key: 'uppsala_lan', text: 'Uppsala län', value: '03' },
  { key: 'haobo', text: 'Håbo', value: '0305' },
  { key: 'alvkarleby', text: 'Älvkarleby', value: '0319' },
  { key: 'knivsta', text: 'Knivsta', value: '0330' },
  { key: 'heby', text: 'Heby', value: '0331' },
  { key: 'tierp', text: 'Tierp', value: '0360' },
  { key: 'uppsala', text: 'Uppsala', value: '0380' },
  { key: 'enkoping', text: 'Enköping', value: '0381' },
  { key: 'osthammar', text: 'Östhammar', value: '0382' },

  { key: 'sodermanlands_lan', text: 'Södermanlands län', value: '04' },
  { key: 'vingaker', text: 'Vingåker', value: '0428' },
  { key: 'gnesta', text: 'Gnesta', value: '0461' },
  { key: 'nykoping', text: 'Nyköping', value: '0480' },
  { key: 'oxelosund', text: 'Oxelösund', value: '0481' },
  { key: 'flen', text: 'Flen', value: '0482' },
  { key: 'katrineholm', text: 'Katrineholm', value: '0483' },
  { key: 'eskilstuna', text: 'Eskilstuna', value: '0484' },
  { key: 'strangnas', text: 'Strängnäs', value: '0486' },
  { key: 'trosa', text: 'Trosa', value: '0488' },

  { key: 'ostergotlands_lan', text: 'Östergötlands län', value: '05' },
  { key: 'odeshog', text: 'Ödeshög', value: '0509' },
  { key: 'ydre', text: 'Ydre', value: '0512' },
  { key: 'kinda', text: 'Kinda', value: '0513' },
  { key: 'boxholm', text: 'Boxholm', value: '0560' },
  { key: 'atvidaberg', text: 'Åtvidaberg', value: '0561' },
  { key: 'finspang', text: 'Finspång', value: '0562' },
  { key: 'valdemarsvik', text: 'Valdemarsvik', value: '0563' },
  { key: 'linkoping', text: 'Linköping', value: '0580' },
  { key: 'norrkoping', text: 'Norrköping', value: '0581' },
  { key: 'soderkoping', text: 'Söderköping', value: '0582' },
  { key: 'motala', text: 'Motala', value: '0583' },
  { key: 'vadstena', text: 'Vadstena', value: '0584' },
  { key: 'mjolby', text: 'Mjölby', value: '0586' },

  { key: 'jonkopings_lan', text: 'Jönköpings län', value: '06' },
  { key: 'aneby', text: 'Aneby', value: '0604' },
  { key: 'gnosjo', text: 'Gnosjö', value: '0617' },
  { key: 'mullsjo', text: 'Mullsjö', value: '0642' },
  { key: 'habo', text: 'Habo', value: '0643' },
  { key: 'gislaved', text: 'Gislaved', value: '0662' },
  { key: 'vaggeryd', text: 'Vaggeryd', value: '0665' },
  { key: 'jonkoping', text: 'Jönköping', value: '0680' },
  { key: 'nassjo', text: 'Nässjö', value: '0682' },
  { key: 'varnamo', text: 'Värnamo', value: '0683' },
  { key: 'savsjo', text: 'Sävsjö', value: '0684' },
  { key: 'vetlanda', text: 'Vetlanda', value: '0685' },
  { key: 'eksjo', text: 'Eksjö', value: '0686' },
  { key: 'tranas', text: 'Tranås', value: '0687' },

  { key: 'kronobergs_lan', text: 'Kronobergs län', value: '07' },
  { key: 'uppvidinge', text: 'Uppvidinge', value: '0760' },
  { key: 'lessebo', text: 'Lessebo', value: '0761' },
  { key: 'tingsryd', text: 'Tingsryd', value: '0763' },
  { key: 'alvesta', text: 'Alvesta', value: '0764' },
  { key: 'almhult', text: 'Älmhult', value: '0765' },
  { key: 'markaryd', text: 'Markaryd', value: '0767' },
  { key: 'vaxjo', text: 'Växjö', value: '0780' },
  { key: 'ljungby', text: 'Ljungby', value: '0781' },

  { key: 'kalmar_lan', text: 'Kalmar län', value: '08' },
  { key: 'hogsby', text: 'Högsby', value: '0821' },
  { key: 'torsas', text: 'Torsås', value: '0834' },
  { key: 'morbylanga', text: 'Mörbylånga', value: '0840' },
  { key: 'hultsfred', text: 'Hultsfred', value: '0860' },
  { key: 'monsteras', text: 'Mönsterås', value: '0861' },
  { key: 'emmaboda', text: 'Emmaboda', value: '0862' },
  { key: 'kalmar', text: 'Kalmar', value: '0880' },
  { key: 'nybro', text: 'Nybro', value: '0881' },
  { key: 'oskarshamn', text: 'Oskarshamn', value: '0882' },
  { key: 'vastervik', text: 'Västervik', value: '0883' },
  { key: 'vimmerby', text: 'Vimmerby', value: '0884' },
  { key: 'borgholm', text: 'Borgholm', value: '0885' },

  { key: 'gotlands_lan', text: 'Gotlands län', value: '09' },
  { key: 'gotland', text: 'Gotland', value: '0980' },

  { key: 'blekinge_lan', text: 'Blekinge län', value: '10' },
  { key: 'olofstrom', text: 'Olofström', value: '1060' },
  { key: 'karlskrona', text: 'Karlskrona', value: '1080' },
  { key: 'ronneby', text: 'Ronneby', value: '1081' },
  { key: 'karlshamn', text: 'Karlshamn', value: '1082' },
  { key: 'solvesborg', text: 'Sölvesborg', value: '1083' },

  { key: 'skane_lan', text: 'Skåne län', value: '12' },
  { key: 'svalov', text: 'Svalöv', value: '1214' },
  { key: 'staffanstorp', text: 'Staffanstorp', value: '1230' },
  { key: 'burlov', text: 'Burlöv', value: '1231' },
  { key: 'vellinge', text: 'Vellinge', value: '1233' },
  { key: 'ostra_goinge', text: 'Östra Göinge', value: '1256' },
  { key: 'orkelljunga', text: 'Örkelljunga', value: '1257' },
  { key: 'bjuv', text: 'Bjuv', value: '1260' },
  { key: 'kavlinge', text: 'Kävlinge', value: '1261' },
  { key: 'lomma', text: 'Lomma', value: '1262' },
  { key: 'svedala', text: 'Svedala', value: '1263' },
  { key: 'skurup', text: 'Skurup', value: '1264' },
  { key: 'sjobo', text: 'Sjöbo', value: '1265' },
  { key: 'horby', text: 'Hörby', value: '1266' },
  { key: 'hoor', text: 'Höör', value: '1267' },
  { key: 'tomelilla', text: 'Tomelilla', value: '1270' },
  { key: 'bromolla', text: 'Bromölla', value: '1272' },
  { key: 'osby', text: 'Osby', value: '1273' },
  { key: 'perstorp', text: 'Perstorp', value: '1275' },
  { key: 'klippan', text: 'Klippan', value: '1276' },
  { key: 'astorp', text: 'Åstorp', value: '1277' },
  { key: 'bastad', text: 'Båstad', value: '1278' },
  { key: 'Malmö', text: 'Malmö', value: '1280' },
  { key: 'lund', text: 'Lund', value: '1281' },
  { key: 'landskrona', text: 'Landskrona', value: '1282' },
  { key: 'helsingborg', text: 'Helsingborg', value: '1283' },
  { key: 'hoganas', text: 'Höganäs', value: '1284' },
  { key: 'eslov', text: 'Eslöv', value: '1285' },
  { key: 'ystad', text: 'Ystad', value: '1286' },
  { key: 'trelleborg', text: 'Trelleborg', value: '1287' },
  { key: 'kristianstad', text: 'Kristianstad', value: '1290' },
  { key: 'simrishamn', text: 'Simrishamn', value: '1291' },
  { key: 'angelholm', text: 'Ängelholm', value: '1292' },
  { key: 'hassleholm', text: 'Hässleholm', value: '1293' },

  { key: 'hallands_lan', text: 'Hallands län', value: '13' },
  { key: 'hylte', text: 'Hylte', value: '1315' },
  { key: 'halmstad', text: 'Halmstad', value: '1380' },
  { key: 'laholm', text: 'Laholm', value: '1381' },
  { key: 'falkenberg', text: 'Falkenberg', value: '1382' },
  { key: 'varberg', text: 'Varberg', value: '1383' },
  { key: 'kungsbacka', text: 'Kungsbacka', value: '1384' },

  { key: 'vastra_gotalands_lan', text: 'Västra Götalands län', value: '14' },
  { key: 'harryda', text: 'Härryda', value: '1401' },
  { key: 'partille', text: 'Partille', value: '1402' },
  { key: 'ockero', text: 'Öckerö', value: '1407' },
  { key: 'stenungsund', text: 'Stenungsund', value: '1415' },
  { key: 'tjorn', text: 'Tjörn', value: '1419' },
  { key: 'orust', text: 'Orust', value: '1421' },
  { key: 'sotenas', text: 'Sotenäs', value: '1427' },
  { key: 'munkedal', text: 'Munkedal', value: '1430' },
  { key: 'tanum', text: 'Tanum', value: '1435' },
  { key: 'dals-ed', text: 'Dals-Ed', value: '1438' },
  { key: 'fargelanda', text: 'Färgelanda', value: '1439' },
  { key: 'ale', text: 'Ale', value: '1440' },
  { key: 'lerum', text: 'Lerum', value: '1441' },
  { key: 'vargarda', text: 'Vårgårda', value: '1442' },
  { key: 'bollebygd', text: 'Bollebygd', value: '1443' },
  { key: 'grastorp', text: 'Grästorp', value: '1444' },
  { key: 'essunga', text: 'Essunga', value: '1445' },
  { key: 'karlsborg', text: 'Karlsborg', value: '1446' },
  { key: 'gullspång', text: 'Gullspång', value: '1447' },
  { key: 'tranemo', text: 'Tranemo', value: '1452' },
  { key: 'bengtsfors', text: 'Bengtsfors', value: '1460' },
  { key: 'mellerud', text: 'Mellerud', value: '1461' },
  { key: 'lilla_edet', text: 'Lilla Edet', value: '1462' },
  { key: 'mark', text: 'Mark', value: '1463' },
  { key: 'svenljunga', text: 'Svenljunga', value: '1465' },
  { key: 'herrljunga', text: 'Herrljunga', value: '1466' },
  { key: 'vara', text: 'Vara', value: '1470' },
  { key: 'gotene', text: 'Götene', value: '1471' },
  { key: 'tibro', text: 'Tibro', value: '1472' },
  { key: 'toreboda', text: 'Töreboda', value: '1473' },
  { key: 'goteborg', text: 'Göteborg', value: '1480' },
  { key: 'molndal', text: 'Mölndal', value: '1481' },
  { key: 'kungalv', text: 'Kungälv', value: '1482' },
  { key: 'lysekil', text: 'Lysekil', value: '1484' },
  { key: 'uddevalla', text: 'Uddevalla', value: '1485' },
  { key: 'stromstad', text: 'Strömstad', value: '1486' },
  { key: 'vanersborg', text: 'Vänersborg', value: '1487' },
  { key: 'trollhattan', text: 'Trollhättan', value: '1488' },
  { key: 'alingsas', text: 'Alingsås', value: '1489' },
  { key: 'boras', text: 'Borås', value: '1490' },
  { key: 'ulricehamn', text: 'Ulricehamn', value: '1491' },
  { key: 'amal', text: 'Åmål', value: '1492' },
  { key: 'mariestad', text: 'Mariestad', value: '1493' },
  { key: 'lidkoping', text: 'Lidköping', value: '1494' },
  { key: 'skara', text: 'Skara', value: '1495' },
  { key: 'skovde', text: 'Skövde', value: '1496' },
  { key: 'hjo', text: 'Hjo', value: '1497' },
  { key: 'tidaholm', text: 'Tidaholm', value: '1498' },
  { key: 'falkoping', text: 'Falköping', value: '1499' },

  { key: 'varmlands_lan', text: 'Värmlands län', value: '17' },
  { key: 'kil', text: 'Kil', value: '1715' },
  { key: 'eda', text: 'Eda', value: '1730' },
  { key: 'torsby', text: 'Torsby', value: '1737' },
  { key: 'storfors', text: 'Storfors', value: '1760' },
  { key: 'hammaro', text: 'Hammarö', value: '1761' },
  { key: 'munkfors', text: 'Munkfors', value: '1762' },
  { key: 'forshaga', text: 'Forshaga', value: '1763' },
  { key: 'grums', text: 'Grums', value: '1764' },
  { key: 'arjang', text: 'Årjäng', value: '1765' },
  { key: 'sunne', text: 'Sunne', value: '1766' },
  { key: 'karlstad', text: 'Karlstad', value: '1780' },
  { key: 'kristinehamn', text: 'Kristinehamn', value: '1781' },
  { key: 'filipstad', text: 'Filipstad', value: '1782' },
  { key: 'hagfors', text: 'Hagfors', value: '1783' },
  { key: 'arvika', text: 'Arvika', value: '1784' },
  { key: 'saffle', text: 'Säffle', value: '1785' },

  { key: 'orebro_lan', text: 'Örebro län', value: '18' },
  { key: 'lekeberg', text: 'Lekeberg', value: '1814' },
  { key: 'laxa', text: 'Laxå', value: '1860' },
  { key: 'hallsberg', text: 'Hallsberg', value: '1861' },
  { key: 'degerfors', text: 'Degerfors', value: '1862' },
  { key: 'hallefors', text: 'Hällefors', value: '1863' },
  { key: 'ljusnarsberg', text: 'Ljusnarsberg', value: '1864' },
  { key: 'orebro', text: 'Örebro', value: '1880' },
  { key: 'kumla', text: 'Kumla', value: '1881' },
  { key: 'askersund', text: 'Askersund', value: '1882' },
  { key: 'karlskoga', text: 'Karlskoga', value: '1883' },
  { key: 'nora', text: 'Nora', value: '1884' },
  { key: 'lindesberg', text: 'Lindesberg', value: '1885' },

  { key: 'vastmanlands_lan', text: 'Västmanlands län', value: '19' },
  { key: 'skinnskatteberg', text: 'Skinnskatteberg', value: '1904' },
  { key: 'surahammar', text: 'Surahammar', value: '1907' },
  { key: 'kungsor', text: 'Kungsör', value: '1960' },
  { key: 'hallstahammar', text: 'Hallstahammar', value: '1961' },
  { key: 'norberg', text: 'Norberg', value: '1962' },
  { key: 'vasteras', text: 'Västerås', value: '1980' },
  { key: 'sala', text: 'Sala', value: '1981' },
  { key: 'fagersta', text: 'Fagersta', value: '1982' },
  { key: 'koping', text: 'Köping', value: '1983' },
  { key: 'arboga', text: 'Arboga', value: '1984' },

  { key: 'dalarnas_lan', text: 'Dalarnas län', value: '20' },
  { key: 'vansbro', text: 'Vansbro', value: '2021' },
  { key: 'malung-salen', text: 'Malung-Sälen', value: '2023' },
  { key: 'gagnef', text: 'Gagnef', value: '2026' },
  { key: 'leksand', text: 'Leksand', value: '2029' },
  { key: 'rattvik', text: 'Rättvik', value: '2031' },
  { key: 'orsa', text: 'Orsa', value: '2034' },
  { key: 'alvdalen', text: 'Älvdalen', value: '2039' },
  { key: 'smedjebacken', text: 'Smedjebacken', value: '2061' },
  { key: 'mora', text: 'Mora', value: '2062' },
  { key: 'falun', text: 'Falun', value: '2080' },
  { key: 'borlange', text: 'Borlänge', value: '2081' },
  { key: 'sater', text: 'Säter', value: '2082' },
  { key: 'hedemora', text: 'Hedemora', value: '2083' },
  { key: 'avesta', text: 'Avesta', value: '2084' },
  { key: 'ludvika', text: 'Ludvika', value: '2085' },

  { key: 'gavleborgs_lan', text: 'Gävleborgs län', value: '21' },
  { key: 'ockelbo', text: 'Ockelbo', value: '2101' },
  { key: 'hofors', text: 'Hofors', value: '2104' },
  { key: 'ovanaker', text: 'Ovanåker', value: '2121' },
  { key: 'nordanstig', text: 'Nordanstig', value: '2132' },
  { key: 'ljusdal', text: 'Ljusdal', value: '2161' },
  { key: 'gavle', text: 'Gävle', value: '2180' },
  { key: 'sandviken', text: 'Sandviken', value: '2181' },
  { key: 'soderhamn', text: 'Söderhamn', value: '2182' },
  { key: 'bollnas', text: 'Bollnäs', value: '2183' },
  { key: 'hudiksvall', text: 'Hudiksvall', value: '2184' },

  { key: 'vasternorrlands_lan', text: 'Västernorrlands län', value: '22' },
  { key: 'ange', text: 'Ånge', value: '2260' },
  { key: 'timra', text: 'Timrå', value: '2262' },
  { key: 'harnosand', text: 'Härnösand', value: '2280' },
  { key: 'sundsvall', text: 'Sundsvall', value: '2281' },
  { key: 'kramfors', text: 'Kramfors', value: '2282' },
  { key: 'solleftea', text: 'Sollefteå', value: '2283' },
  { key: 'ornskoldsvik', text: 'Örnsköldsvik', value: '2284' },

  { key: 'jamtlands_lan', text: 'Jämtlands län', value: '23' },
  { key: 'ragunda', text: 'Ragunda', value: '2303' },
  { key: 'bracke', text: 'Bräcke', value: '2305' },
  { key: 'krokom', text: 'Krokom', value: '2309' },
  { key: 'stromsund', text: 'Strömsund', value: '2313' },
  { key: 'are', text: 'Åre', value: '2321' },
  { key: 'berg', text: 'Berg', value: '2326' },
  { key: 'harjedalen', text: 'Härjedalen', value: '2361' },
  { key: 'ostersund', text: 'Östersund', value: '2380' },

  { key: 'vasterbottens_lan', text: 'Västerbottens län', value: '24' },
  { key: 'nordmaling', text: 'Nordmaling', value: '2401' },
  { key: 'bjurholm', text: 'Bjurholm', value: '2403' },
  { key: 'vindeln', text: 'Vindeln', value: '2404' },
  { key: 'robertsfors', text: 'Robertsfors', value: '2409' },
  { key: 'norsjo', text: 'Norsjö', value: '2417' },
  { key: 'mala', text: 'Malå', value: '2418' },
  { key: 'storuman', text: 'Storuman', value: '2421' },
  { key: 'sorsele', text: 'Sorsele', value: '2422' },
  { key: 'dorotea', text: 'Dorotea', value: '2425' },
  { key: 'vannas', text: 'Vännäs', value: '2460' },
  { key: 'vilhelmina', text: 'Vilhelmina', value: '2462' },
  { key: 'asele', text: 'Åsele', value: '2463' },
  { key: 'umea', text: 'Umeå', value: '2480' },
  { key: 'lycksele', text: 'Lycksele', value: '2481' },
  { key: 'skelleftea', text: 'Skellefteå', value: '2482' },

  { key: 'norrbottens_lan', text: 'Norrbottens län', value: '25' },
  { key: 'arvidsjaur', text: 'Arvidsjaur', value: '2505' },
  { key: 'arjeplog', text: 'Arjeplog', value: '2506' },
  { key: 'jokkmokk', text: 'Jokkmokk', value: '2510' },
  { key: 'overkalix', text: 'Överkalix', value: '2513' },
  { key: 'kalix', text: 'Kalix', value: '2514' },
  { key: 'overtornea', text: 'Övertorneå', value: '2518' },
  { key: 'pajala', text: 'Pajala', value: '2521' },
  { key: 'gallivare', text: 'Gällivare', value: '2523' },
  { key: 'alvsbyn', text: 'Älvsbyn', value: '2560' },
  { key: 'lulea', text: 'Luleå', value: '2580' },
  { key: 'pitea', text: 'Piteå', value: '2581' },
  { key: 'boden', text: 'Boden', value: '2582' },
  { key: 'haparanda', text: 'Haparanda', value: '2583' },
  { key: 'kiruna', text: 'Kiruna', value: '2584' }
]
